;; Automatically generated by GNUmakefile.
((coq-mode . ((eval . (let ((default-directory (locate-dominating-file
                                                buffer-file-name ".dir-locals.el")))
                        (make-local-variable 'coq-load-path)
                        (setq coq-load-path `(,(expand-file-name ".") ,(expand-file-name "./charge") ,(expand-file-name "./x86") ,(expand-file-name "./x86/win") ,(expand-file-name "./x86/lib/regexp"))))))))
